<?php

namespace MDPlanningBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * DateLouvreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DateLouvreRepository extends EntityRepository
{
    public function isBookable ($nbBillet, $dateReservation) {
        //Recherche élément dans la base concernant la date souhaité
        /* SI aucune réservation n'existe
        *       SI nbBillet <MAX ALORS 
        *           retourne TRUE
        *       SINON
        *           retourne FALSE
        * SINON
        *       SI nbBillet + nbBilletsDéjàRéservé < MAX ALORS
        *           retourne TRUE
        *       SINON
        *           retourne FALSE
        */
        
        
    }
}
