<?php

namespace MDPlanningBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * LeLouvreEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LeLouvreEventRepository extends EntityRepository
{
}
