oc_core:
    resource: "@OCCoreBundle/Controller/"
    type:     annotation
    prefix:   /

oc_commande:
    resource: "@OCCommandeBundle/Controller/"
    type:     annotation
    prefix:   /commande

fos_js_routing:
    resource: "@FOSJsRoutingBundle/Resources/config/routing/routing.xml"

adesigns_calendar:
    resource: "@ADesignsCalendarBundle/Resources/config/routing.xml"