<?php

namespace OC\CommandeBundle\Repository;

/**
 * CommandeTarifRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeTarifRepository extends \Doctrine\ORM\EntityRepository
{
}
