<?php

namespace OC\CommandeBundle\Repository;
use Doctrine\ORM\QueryBuilder; 
/**
 * CommandeGlobaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeGlobaleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBySessionId($sessionId) {
        $qb = $this->createQueryBuilder('a');
        $qb->where('a.sessionId = :sessionId')
            ->setParameter('sessionId', $sessionId)
            ->orderBy('a.date_commande','DESC');
        return $qb->getQuery()->getResult();
    }
    
}
