<?php

namespace OC\CommandeBundle\Repository;
use Doctrine\ORM\QueryBuilder; 
use OC\CoreBundle\Entity\Mylog;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
/**
 * CommandeGlobaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeGlobaleRepository extends \Doctrine\ORM\EntityRepository
{
    public function findBySessionId($sessionId) {
        $qb = $this->createQueryBuilder('a');
        $qb->where('a.sessionId = :sessionId')
            ->setParameter('sessionId', $sessionId)
            ->orderBy('a.date_commande','DESC');
        return $qb->getQuery()->getResult();
    }
    public function countByVisitDate(Controller &$ctrl, \Datetime $la_date) {
        $date_apres = new \Datetime($la_date->format('Y-m-d').' + 1 day');
        $qb = $this->createQueryBuilder('a');
        $qb->select('SUM(a.nbBillets) AS total')
        	->where('a.dateReservation >= \''.$la_date->format('Y-m-d').'\'')
            ->andwhere('a.dateReservation < \''.$date_apres->format('Y-m-d').'\'')
        	->andWhere('a.paid = 1');
        $query = $qb->getQuery();
        $mylog = new Mylog();
        $mylog->add($ctrl, 'QueryBuilder SQL',$query->getSql());
        $mylog = new Mylog();
        $mylog->add($ctrl, 'QueryBuilder Parameter',$query->getParameters());
        return $query->getResult();
    }
}
