<?php

namespace OC\CommandeBundle\Repository;

/**
 * CommandeGlobaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandeGlobaleRepository extends \Doctrine\ORM\EntityRepository
{
}
