<?php

namespace OC\CommandeBundle\Repository;

/**
 * TarifSeniorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifSeniorRepository extends \Doctrine\ORM\EntityRepository
{
}
