<?php

namespace OC\CommandeBundle\Repository;

/**
 * TarifReduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifReduitRepository extends \Doctrine\ORM\EntityRepository
{
}
