<?php

namespace OC\CommandeBundle\Repository;

/**
 * TarifEnfantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifEnfantRepository extends \Doctrine\ORM\EntityRepository
{
}
