<?php

namespace OC\CommandeBundle\Repository;

/**
 * TarifFamilleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifFamilleRepository extends \Doctrine\ORM\EntityRepository
{
}
