<?php

namespace OC\CommandeBundle\Repository;

/**
 * TarifNormalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TarifNormalRepository extends \Doctrine\ORM\EntityRepository
{
}
