<?php

namespace OC\CoreBundle\Repository;

/**
 * InitCommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InitCommandeRepository extends \Doctrine\ORM\EntityRepository
{
}
