<?php

namespace OC\CoreBundle\Repository;

/**
 * MylogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MylogRepository extends \Doctrine\ORM\EntityRepository
{
}
