services:
#    md_planning.example:
#        class: MDPlanningBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
    md_planning.calendar_listener:
        class: MDPlanningBundle\EventListener\CalendarEventListener
        arguments: ["@doctrine.orm.entity_manager"]
        tags:
            - { name: kernel.event_listener, event: calendar.load_events, method: loadEvents }
            